sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: https://oss-cn-shenzhen.aliyuncs.com
    access-key-id: .......
    access-key-secret: .......
    bucket-name: mwm-sky-take-out
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: .......
    secret: .......
    mchid: 1111
    mch-serial-no: 111
    private-key-file-path: 1111
    api-v3-key: D:\pay\apiclient_key.pem
    we-chat-pay-cert-file-path: D:\pay\wechat.pem
    # 本地服务地址 https://18b7bf2f.r15.cpolar.top cpolar 生成的内外穿透地址
    notify-url: https://18b7bf2f.r15.cpolar.top/notify/paySuccess
    refund-notify-url: https://18b7bf2f.r15.cpolar.top/notify/refundSuccess